name: Release
on:
  push:
    branches: [main]
permissions:
  contents: write
env:
  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    if: github.event.head_commit.author.name != 'GitHub Actions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "devops@yev.ai"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Prepare
        run: |
          bun install
          bun run build
          bun run lint
          bun run change:ver
      - name: Publish
        run: bun run change:pub
      - name: Push Tags
        run: git push --follow-tags
