name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      # - name: Create Release PR or Publish
      #   uses: changesets/action@v1
      #   with:
      #     publish: bun run publish
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
